language: csharp
mono: none
dotnet: 2.1.502
solution: MobileDetector.Core.sln
install:
  - dotnet tool install -g coveralls.net --version 1.0.0
script:
  - dotnet restore
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - csmacnz.Coveralls --opencover -i /MobileDetector.Core.Tests/coverage.opencover.xml --useRelativePaths