language: csharp
mono: none
solution: MobileDetector.Core.sln
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet restore
  - dotnet build
  - dotnet test